### ISSUE TITLE
ModuleNotFoundError: No module named 'wsiprocess.converters'

### ISSUE THREAD

**Issue by Arghya999** [tand826/WSIPatcher#1]
command :-  python wsipatcher.py generates :- 

Traceback (most recent call last):
  File "wsipatcher.py", line 6, in <module>
    import wsiprocess as wp
  File "/home/AG00638479/.conda/envs/digital_pathology_conda/lib/python3.6/site-packages/wsiprocess/__init__.py", line 5, in <module>
    from .converter import Converter as converter
  File "/home/AG00638479/.conda/envs/digital_pathology_conda/lib/python3.6/site-packages/wsiprocess/converter.py", line 4, in <module>
    from .converters import (
ModuleNotFoundError: No module named 'wsiprocess.converters'

**Comment by tand826** [comment]
Thanks for the comment.

Please see [issue in wsiprocess](https://github.com/tand826/wsiprocess/issues/8#issuecomment-646046325)
